sudo: required

language: node_js
node_js:
  - "node"

services:
  - docker

before_install:
  - echo "Building Container"
  - docker build -t nateinaction/wunderground-graphql:latest .

after_success:
  - echo "Pushing to Docker Hub"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push nateinaction/wunderground-graphql;
    fi
